env:
  - RUBYOPT=-W0
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - ruby-head
  - jruby-head
branches:
  only: [master]
sudo: false
cache: bundler
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
bundler_args: "--jobs 4"
